# Generated by Django 5.1.6 on 2025-03-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto_SENA', '0006_alter_pedido_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('bancolombia', 'Bancolombia'), ('nequi', 'Nequi'), ('daviplata', 'DaviPlata'), ('contra-entrega', 'ContraEntrega')], max_length=20),
        ),
    ]
